name: diwa
description: "A learning app for Filipino language"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  firebase_auth_web: ^5.14.2 
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  intl: ^0.20.2
  audioplayers: ^6.4.0
  path_provider: ^2.1.1
  flutter_tts: ^4.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

    
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700